### PR TITLE
Fix parsing 0 as FLOAT

### LINKED ISSUE #15: `FLOAT` never matches `0`
For example, running `FLOAT(-1, 1)` against `0` gives:
```
0
 ^


ERROR: line 1 character 2 of testdata doesn't match FLOAT(-(1),1): prefix zero(s)
```

### PR DESCRIPTION
**Pull request by RagnarGrootKoerkamp**
Fixes #15 , but would be good if somebody could independently confirm that that issue is an issue indeed:

It's failing when I rebuild checktestdata from release, but working for an older checktestdata binary in a docker image.
It was probably introduced by c628fee75850863b83f85aa41ae60e826c38c419, and the binary checktestdata was probably built before that time.

### CODE REVIEW

**Review by eldering — COMMENTED** [review]
LGTM, but maybe also add a few test inputs with floats in scientific notation?

File: libchecktestdata.cc [hunk 1]
```diff
@@ -1003,12 +1003,14 @@ void checktoken(const command& cmd)
 		if ( !isdigit(data.peek()) ) error("digit expected");
 		size_t digitpos = data.pos(), dotpos = string::npos;
 		char first_digit = data.peek();
+		size_t num_leading_digits = 0;
 		while ( (isdigit(data.peek()) ||
 		         (dotpos==string::npos && digitpos!=data.pos() && data.peek()=='.')) ) {
 			if ( data.readchar()=='.' ) dotpos = data.pos()-1;
+			else if(dotpos == string::npos) ++num_leading_digits;
```
Comment (eldering) [inline libchecktestdata.cc:1010]: I would remove the `else`: it doesn't change the logic, since in the `if` clause `dotpos` would anyways be changed away from `string::npos` and I think it simplifies understanding the code.

**Review by eldering — COMMENTED** [review]
Two small comments, but in general LGTM. Nice adding these tests already!

**Comment by RagnarGrootKoerkamp** [comment]
@eldering both done. Changed to code a bit more to also reject leading zeros in the exponent.

**Review by eldering — APPROVED** [review]
